import type { GeneratedSiteContent, IntakeFormData } from "@/types";

interface Props {
  content: GeneratedSiteContent;
  intake: IntakeFormData;
}

export default function FooterSection({ content, intake }: Props) {
  const year = new Date().getFullYear();

  return (
    <footer
      style={{
        background: "var(--primary)",
        color: "rgba(255,255,255,0.6)",
        padding: "56px 0 32px",
      }}
    >
      <div className="px-6 md:px-12 lg:px-24 max-w-screen-xl mx-auto">
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
            gap: "40px",
            marginBottom: "48px",
          }}
        >
          {/* Brand */}
          <div>
            <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "14px" }}>
              {intake.logoDataUrl ? (
                // eslint-disable-next-line @next/next/no-img-element
                <img src={intake.logoDataUrl} alt="logo" style={{ height: "32px", objectFit: "contain" }} />
              ) : (
                <div
                  style={{
                    width: "32px",
                    height: "32px",
                    background: "var(--accent)",
                    borderRadius: "8px",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    color: "white",
                    fontWeight: 700,
                    fontSize: "16px",
                  }}
                >
                  {content.brandName.charAt(0)}
                </div>
              )}
              <span
                style={{
                  color: "white",
                  fontFamily: "var(--h-font)",
                  fontWeight: 600,
                  fontSize: "17px",
                }}
              >
                {content.brandName}
              </span>
            </div>
            <p style={{ fontSize: "13px", lineHeight: 1.7, maxWidth: "220px" }}>
              {content.tagline}
            </p>
          </div>

          {/* Quick Links */}
          <div>
            <h4 style={{ color: "white", fontSize: "13px", fontWeight: 600, letterSpacing: "0.08em", textTransform: "uppercase", marginBottom: "16px" }}>
              Quick Links
            </h4>
            <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
              {["Services", "About", "FAQ", "Contact"].map((link) => (
                <a
                  key={link}
                  href={`#${link.toLowerCase()}`}
                  style={{ color: "rgba(255,255,255,0.5)", fontSize: "14px", textDecoration: "none", transition: "color 0.2s" }}
                >
                  {link}
                </a>
              ))}
            </div>
          </div>

          {/* Contact */}
          <div>
            <h4 style={{ color: "white", fontSize: "13px", fontWeight: 600, letterSpacing: "0.08em", textTransform: "uppercase", marginBottom: "16px" }}>
              Contact
            </h4>
            <div style={{ display: "flex", flexDirection: "column", gap: "10px", fontSize: "14px" }}>
              {intake.phone && (
                <a href={`tel:${intake.phone}`} style={{ color: "rgba(255,255,255,0.5)", textDecoration: "none" }}>
                  {intake.phone}
                </a>
              )}
              {intake.email && (
                <a href={`mailto:${intake.email}`} style={{ color: "rgba(255,255,255,0.5)", textDecoration: "none" }}>
                  {intake.email}
                </a>
              )}
              {intake.city && (
                <span style={{ color: "rgba(255,255,255,0.5)" }}>{intake.city}</span>
              )}
            </div>
          </div>
        </div>

        {/* Bottom bar */}
        <div
          style={{
            borderTop: "1px solid rgba(255,255,255,0.08)",
            paddingTop: "24px",
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            flexWrap: "wrap",
            gap: "12px",
          }}
        >
          <p style={{ fontSize: "13px" }}>
            © {year} {content.brandName}. All rights reserved.
          </p>
          <p style={{ fontSize: "12px", color: "rgba(255,255,255,0.25)" }}>
            Site generated by SiteGenAI
          </p>
        </div>
      </div>
    </footer>
  );
}
